### ISSUE TITLE
Add auto-impl of the `From<T> for u8` (and other types)

### ISSUE THREAD

**Issue by nyurik** [matthewjberger/bytenum#1]
When working with enums, frequently the conversion is needed in both direction - `try_from<ReprT> for EnumT` and `from<EnumT> for ReprT`.  Please consider adding another derive macro, e.g. `BytenumFrom`.

**Comment by matthewjberger** [comment]
Hello @nyurik! I have some good news. I made another crate creates both conversion methods, with the intent of replacing this one. Hope it works out for you! 

https://crates.io/crates/enum2repr
